(class List (Object) ()
       (method list? (self)
	       #t))

(class Cons (List) (head tail)
       (method pair? (self)
	       #t)
       (method null? (self)
	       #f))

(class Nil  (List) ()
       (method pair? (self)
	       #f)
       (method null? (self)
	       #t))

(define (cons a b)
  (let ([obj (new Cons)])
    (slot-set! obj head a)
    (slot-set! obj tail b)
    obj))

(define (car pair)
  (slot-ref pair head))

(define (cdr pair)
  (slot-ref pair tail))

(define (caar xs) (car (car xs)))
(define (cdar xs) (cdr (car xs)))
(define (cadr xs) (car (cdr xs)))
(define (cddr xs) (cdr (cdr xs)))
(define (caaar xs) (car (car (car xs))))
(define (cdaar xs) (cdr (car (car xs))))
(define (cadar xs) (car (cdr (car xs))))
(define (cddar xs) (cdr (cdr (car xs))))
(define (caadr xs) (car (car (cdr xs))))
(define (cdadr xs) (cdr (car (cdr xs))))
(define (caddr xs) (car (cdr (cdr xs))))
(define (cdddr xs) (cdr (cdr (cdr xs))))
(define (caaaar xs) (car (car (car (car xs)))))
(define (cdaaar xs) (cdr (car (car (car xs)))))
(define (cadaar xs) (car (cdr (car (car xs)))))
(define (cddaar xs) (cdr (cdr (car (car xs)))))
(define (caadar xs) (car (car (cdr (car xs)))))
(define (cdadar xs) (cdr (car (cdr (car xs)))))
(define (caddar xs) (car (cdr (cdr (car xs)))))
(define (cdddar xs) (cdr (cdr (cdr (car xs)))))
(define (caaadr xs) (car (car (car (cdr xs)))))
(define (cdaadr xs) (cdr (car (car (cdr xs)))))
(define (cadadr xs) (car (cdr (car (cdr xs)))))
(define (cddadr xs) (cdr (cdr (car (cdr xs)))))
(define (caaddr xs) (car (car (cdr (cdr xs)))))
(define (cdaddr xs) (cdr (car (cdr (cdr xs)))))
(define (cadddr xs) (car (cdr (cdr (cdr xs)))))
(define (cddddr xs) (cdr (cdr (cdr (cdr xs)))))

(define nil (new Nil))
(define (null? x)
  (. x (null?)))

(define (length xs)
  (if (null? xs)
      0
      (+ 1 (length (cdr xs)))))

(define (map f xs)
  (if (null? xs)
      nil
      (cons (f (car xs))
	    (map f (cdr xs)))))

