
(define +)
(define +.)
(define -)
(define -.)
(define *)
(define *.)
(define /)

(define <)
(define <=)
(define >)
(define >=)
(define =)

(define print)
(define trace)
(define Object)

(define-class Math (Object) ())
(define-static-method abs (Math))
(define-static-method acos (Math))
(define-static-method asin (Math))
(define-static-method atan (Math))
(define-static-method atan2 (Math))
(define-static-method ceil (Math))
(define-static-method cos (Math))
(define-static-method exp (Math))
(define-static-method floor (Math))
(define-static-method log (Math))
(define-static-method max (Math))
(define-static-method min (Math))
(define-static-method pow (Math))
(define-static-method random (Math))
(define-static-method round (Math))
(define-static-method sin (Math))
(define-static-method tan (Math))
