(define +)
(define +.)
(define -)
(define -.)
(define *)
(define *.)
(define /)

(define <)
(define <=)
(define >)
(define >=)
(define =)

(define trace)
(define Object)

(class Math (Object) ()
       (static abs ())
       (static acos ())
       (static asin ())
       (static atan ())
       (static atan2 ())
       (static ceil ())
       (static cos ())
       (static exp ())
       (static floor ())
       (static log ())
       (static max ())
       (static min ())
       (static pow ())
       (static random ())
       (static round ())
       (static sin ())
       (static tan ()))
